setup:
  type: list
  default: 'staff, 3'
  description: |
    Each line should be in the format of "<code>tag</code>, <code>ID</code>".<br/><br/>
  

    The topic ID is the first number in its url, for example /t/welcome-to-discourse/<b>8</b>/3</li><br/><br/>

  
    <p>For performance reasons it's recommended that you close  sidebar topics so there aren't any replies</p>

sidebar_side: 
  default: right
  type: enum
  choices: 
    - left
    - right

stick_on_scroll: 
  default: true
  description: |
    When checked sidebar has a sticky position on scroll